# Propiedades de la BD
<<<<<<< HEAD
<<<<<<< HEAD
# spring.datasource.url=jdbc:postgresql://localhost:5432/alumnosDB
spring.datasource.url=jdbc:${{DATABASE_URL}}
=======
spring.datasource.url=jdbc:${DATABASE_URL}
>>>>>>> 1f24d57057815710f6ad16b9fca4f82a8f8e8d9b
=======
spring.datasource.url=${DATABASE_URL}
>>>>>>> 0bd0e3972bab8b9238617e212391638911a11421
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=${{PGPASSWORD}}
=======
spring.datasource.password=${PGPASSWORD}
>>>>>>> 1f24d57057815710f6ad16b9fca4f82a8f8e8d9b

# Configuracion del Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion del Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
