# Propiedades de la BD
# spring.datasource.url=jdbc:postgresql://localhost:5432/alumnosDB
# spring.datasource.username=postgres
# spring.datasource.password=admin

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=postgres
spring.datasource.password=${PGPASSWORD}

# Configuracion del Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion del Hibernate
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
